Repository netlify/explorers, pull requests merged in 2020-12, with the labels that each got.

#413 fix (#401): add spacing to mission tracker on mobile
  src/pages/learn/[mission]/Stage.module.css
Labels: type: bug

#432 fix: (#427): turn margin-top value of profile-page class into padding-top
  src/pages/Profile.module.css
Labels: type: bug

#412 fix (#403): nav padding issue
  src/components/Navigation.module.css
Labels: type: bug

#434 adds link to content contribution guide
  README.md
Labels: type: documentation

#436 fix: increase padding for login nudge
  src/components/LoginNudge.module.css
Labels: type: bug

#435 chore: very important comment cleanup
  src/util/cloudinary.js
Labels: type: chore
